[package]
name = "surge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version = "0.86.0", features = ["runtime", "derive", "ws"] }
k8s-openapi = { version = "0.20.0", features = ["latest"] }
futures = "0.3.17"
serde_json = "1.0.68"
tokio = { version = "1.33.0", features=["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.18"
thiserror = "1.0.49"
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"] }
tokio-util = "0.7.9"
url = "2.4.1"
reqwest = { version = "0.11.22", default-features=false, features = ["rustls-tls", "json"] }
